#!/bin/bash

#load modules
module load picard/3.1.1-6z7e4l7
module load samtools/1.19.2-ei3vxnb

workdir=$(pwd)

rawdir=${workdir}/rawdata
trimdir=${workdir}/trimdata
stardir=${workdir}/star
genomedir= **reference genome location**
mkdir ${workdir}/markdup
markdir=${workdir}/markdup

# Calls same loop but for files in the rawdata directory
for f in ${workdir}/rawdata/*_1.fastq.gz
do
R1=$(basename $f | cut -f1 -d.)
base=$(echo $R1 | sed 's/_1//')

# Calls samtools module to sort files generated by the STAR alighnment
samtools sort -@ 8 -o $stardir/${base}.sorted.bam $stardir/${base}-unsort.Aligned.out.bam
# Calls samtools module to index sorted files
samtools index $stardir/${base}.sorted.bam

# Call picard module to mark duplicates
picard MarkDuplicates \ # Calls mark duplicates function
I=$stardir/${base}.sorted.bam \ # Specify input files
O=$markdir/${base}.markdup.bam \ # Specify output files
M=$markdir/${base}.metrics.markdup.txt \ # Speify output metrics file
REMOVE_DUPLICATES=false \ # Tells module not to remove duplicates yet
VALIDATION_STRINGENCY=SILENT # 	Completely suppresses all validation warnings and continues execution without logging them. 
# default VALIDATION_STRINGENCY = strict which Throws an exception and terminates execution immediately upon encountering any validation error. 

# duplicate function which now removes duplicates and generates a new metrics file with the suffix .metrics.rmdup.txt
picard MarkDuplicates \
I=${stardir}/${base}.sorted.bam \
O=${markdir}/${base}.rmdup.bam \
M=${markdir}/${base}.metrics.rmdup.txt \
REMOVE_DUPLICATES=true \
VALIDATION_STRINGENCY=SILENT

done
